### ISSUE TITLE
infantstudies-ubc

### ISSUE THREAD

**Issue by mcfrank** [langcog/mb1-analysis#146]
need to download new error-corrected file

1) Under lab id, we replaced infantstudies-ubc with WerkerIFC. This has been corrected to infantstudies-ubc
2) There were two 2nd session babies that were mislabelled as first session
3) The language criteria for monolingual status were filled in with parent estimates. However, since we are also contributing a bilingual sample, this should (I think) have been filled in using the values we derive from our day-in-the-life questionnaire. These have been replaced - which changes the status of one baby (noted in spreadsheet)
4) Under participant data we noted “error” for trial-level errors. This has been corrected; only session errors are now reported and all trial level errors are reported only in the trial data sheet
5) Three babies were coded with the wrong order (all orders have now been verified by listening to the audio presentation in videos). These have been corrected in the trial-level data.

**Comment by melsod** [comment]
newest version is now in cleaned folders.
