### ISSUE TITLE
babylab-saarland language exposure

### ISSUE THREAD

**Issue by melsod** [langcog/mb1-analysis#150]
Here's the response I got regarding the saarland language exposure data:

"These participants can assumed to be monolingual. **_They have 100% German language exposure but sometimes one parent or relative is frensh._** [emphasis added] But as we only invited participants under the restriction that they are monolingual, I would asume them to be monolingual."

I would be inclined to treat the language2 percentages as correct and subtract from the Language1 (German) percentages.

**Comment by rebeccalundwall** [comment]
I can do this and  handle a few more similar types of issues.  Just assign about 4-8 issues to me that you most want me to handle.

**Comment by melsod** [comment]
@rebeccalundwall Thanks. I think these small data edits/emailing individual labs is probably not the best type of task to have new folks tackle at this stage. There are some other kinds of tasks that might make sense to get a fresh worker on, that I've been thinking it might be good to do before the manuscript goes out. I'll post some of those as issues and assign you?

**Comment by melsod** [comment]
OK, changed one participant from "bilingual" to "monolingual" based on the explicit information that there was only 10% French. Left the other one (where it was listed as 100% German) as "bilingual" because otherwise I'm deleting any record that there was a discrepancy. But this should/will also get treated as monolingual by the R code.
